### ISSUE TITLE
Multitenancy interface missing in AbstractTenantESAR ?

### ISSUE THREAD

**Issue by heutelbeck** [JEEventStore/JCommonDomain#4]
In: org.jeecqrs.common.domain.model.multitenancy.AbstractTenantESAR
I am wondering if this is supposed to implement Multinenancy

i.e.:
```java
public abstract class AbstractTenantESAR<T, OID extends Identity, TID extends Identity>
        extends org.jeecqrs.common.domain.model.AbstractEventSourcedAggregateRoot<T, OID>  implements Multitenancy<TID> {
```

This would relief the developer from declaring the implementation of the interface by itself for each aggregate root in a multi tenancy scenario. Just wondering. I am not yet finished with my first prototype application.

**Comment by lngr** [comment]
Yes, exactly (sorry for the lack of documentation).

The TID is the type of the Tenant ID, for example:

    public class TenantId extends AbstractId<TenantId> {
        public TenantId(String idString) {
            super(idString);
        }
    }

We use it as follows: Our domain classes derive from AbstractTenantESAR:

    public class Patient extends AbstractTenantESAR<Patient, PatientId> {
        public Patient(TenantId tenantId, PatientId patientId, Gender gender, ...) {
            ...
            this.apply(new PatientRegistered(tenantId, patientId, gender, ...));
        }
        protected final void when(PatientRegistered event) {
            this.setTenantId(event.tenantId());
        }
    }

For the repositories, we use a multi-tenant aware repository deriving from

https://github.com/JEEventStore/JCommonDomain/blob/master/persistence-jeeventstore-multitenancy/src/main/java/org/jeecqrs/common/persistence/jeeventstore/AbstractMultiTenancyEventStoreRepository.java

which internally uses a special stream name generator that essentially prefixes the tenantId to the class name:

https://github.com/JEEventStore/JCommonDomain/blob/master/persistence-jeeventstore-multitenancy/src/main/java/org/jeecqrs/common/persistence/jeeventstore/MultiTenancyCanonicalNameESNG.java

I have no public code ready that uses multitenancy, but if needed I can probably prepare a small sample application.

Note: The SagaTracker (in JEECQRS) is currently not yet tenant-aware.

**Comment by lngr** [comment]
(deleted the previous comment because I misunderstood your question)

Yes, you are right, one could possibly add it to make it explicit.

Do you explicitly use the concept of multi tenancy in your aggregate roots? In our projects it's rather an additional ID value and only used as such, and therefore we haven't noticed that `Multitenancy` is missing on the AR base class.

**Comment by heutelbeck** [comment]
Regarding your initial comment: Sagas not supporting Multi tenancy, at this moment I cannot judge the impact.

Other than that I have some hard time to identify the rigth permutation of type declarations for a multi tenant repository interface and implementation:

The Aggregate root:

```java
public class Individual extends
		AbstractTenantESAR<Individual, AgentId, OrganizationId> implements
		MultiTenancy<OrganizationId> {
```

The repository interface:
```java
public interface IndividualRepository
		extends
		Repository<Individual, MultiTenancyId<OrganizationId, AgentId>, Identity> {
}
```

The implementation:

```java
public class IndividualRepositoryImpl
		extends
		AbstractMultiTenancyEventStoreRepository<Individual, OrganizationId, AgentId>
		implements IndividualRepository {
```
or

```java
public class IndividualRepositoryImpl
		extends
		AbstractMultiTenancyEventStoreRepository<Individual, MultiTenancyId<OrganizationId, AgentId>, Identity>
		implements IndividualRepository {

```

The last two do not appear to have the right set of types in their declaration. I suspect I just miss some detail in the use of the generics here. (the way generics are used makes your framework nice though)

Overall I wonder if there is some Interface I am missing (wasn't able to find one in the code). Something like the Repository interface but for multi tenant repositories. 

I already tried intorducing an interface:
```java
public interface MultiTenantRepository<T extends AbstractTenantESAR<T, OID, TID>, TID extends Identity, OID extends Identity, CID extends Identity> {
	boolean exists(TID tenantId, OID id);

	T ofIdentity(TID tenantId, OID id);

	void add(T obj, CID commitId);
}
```

I ran into other issues here with type mismatches. 

I get the feeling I miss something very simple. Could you please give me an example for a multi tenant repository intercace and the matching implementation?

Thanks a lot.

**Comment by lngr** [comment]
Yes, I will prepare a simple example.

**Comment by heutelbeck** [comment]
I think I am slowly approaching the core of my confusion.

Currently I am not able to define an interface for a multi tenant repository, because:
a) There is no interface to extend from
b) Even without one, when defining e.g. Identity ofIdentity(OrganizationId, AgentIdid) the implementing class inheriting from the AbstractMultiTenancyEventStoreRepository cannot implement "ofIdentity" and in the superclass method (and the other typical repository methods) is defined as protected: 
```java
  protected T ofIdentity(TID tenantId, OID id) {
```
So my IndividualRepository cannot change the visibility of the method to public.

So I would be stuck with declaring an interface with new methods with different names calling the protected ones.

Why are these methods protected ? Are using another way of delcaring interfaces and implementing the repository?

**Comment by heutelbeck** [comment]
Ok got it solved, by reverse engineeing the non multi tenant repositories.

* Defined a new inteface: (Iwould suggest to add it to the framework)
```java
public interface MultiTenantRepository<T, OID extends Identity, TID extends Identity, CID extends Identity> {

	public boolean exists(TID tenantId, OID id);

	public T ofIdentity(TID tenantId, OID id);

	public void add(T obj, CID id);

	public void save(T obj, CID id);
}
```

* Derive specific repository interface
```java
public interface IndividualRepository extends
		MultiTenantRepository<Individual, AgentId, OrganizationId, Identity> {

}
```

* Implement the repository, and actually change the visibility of the methods from protected to public
```java
public class IndividualRepositoryImpl
		extends
		AbstractMultiTenancyEventStoreRepository<Individual, AgentId, OrganizationId>
		implements IndividualRepository {

	@EJB
	private EventStore eventStore;

	@Override
	protected String bucketId() {
		return Resources.DOMAIN_BUCKET_ID;
	}

	@Override
	protected EventStore eventStore() {
		return eventStore;
	}

    @Override
    public void add(Individual obj, Identity commitId) {
        super.add(obj, commitId);
    }

    @Override
    public void save(Individual obj, Identity commitId) {
        super.save(obj, commitId);
    }

    @Override
    public Individual ofIdentity(OrganizationId tenantId, AgentId id) {
        return super.ofIdentity(tenantId, id);
    }

    @Override
    public boolean exists(OrganizationId tenantId, AgentId id) {
    	return super.exists(tenantId, id);
    }
}
```

* I still wondery why the methods are protected, as the class ist abstract anyhow.

**Comment by lngr** [comment]
Yes, this is exactly how you'd do it.  Here's a complete working example (without CQRS, just event sourcing and JCommonDomain) exposing a trivial REST interface to be tested with e.g., curl.

https://github.com/JEEventStore/JCommonDomain-Multitenancy-Sample

The methods are protected, because on the one hand we want to provide a default implementation for the most common use cases (exists, add, save, ofIdentity), but on the other hand we don't want to expose all of them to the public api of that repository by default.  (Of course this only matters if someone is not using the interface, but the implementation). If "consumers" of the default implementation want to make them public by default, one can simply do this once per project by overriding their visibility from protected to public in a per-project base class, as in, e.g.

https://github.com/JEEventStore/JCommonDomain-Multitenancy-Sample/blob/master/ejb/src/main/java/org/jeecqrs/example/multitenancy/infra/AbstractMultiTenancyRepository.java

**Comment by lngr** [comment]
Yes, I'll probably add `MultiTenantRepository` to the framework.

**Comment by heutelbeck** [comment]
Thanks. The example application ist straight forward.

**Comment by lngr** [comment]
On second thought, I cannot see a real benefit from marking those methods protected.  I just made all of these methods public, so consumers don't have to do the tedious override. 

I also added the multi tenancy repository as suggested.

The examples are even more concise now, which is nice.

**Comment by heutelbeck** [comment]
Excellent. Less boilerplate for the developer. Thanks.
